'use strict';
let token='',page='Discovery',data=[];
const $=id=>document.getElementById(id);
const pages={'Discovery':'research','Pregame':'research','Live':'research','Wagers':'wagers','Performance':'performance','Exposure':'wagers','Coverage':'coverage','Provider health':'health','Audit':'audit','Limits':'limits'};
const current=()=>new Date().toISOString();
const quote=()=>({id:'unique-quote-id',provider:'manual',provider_event_id:'provider-event-id',event_id:'canonical-event-id',sport:'',league:'',event:'',start_at:current(),market:'moneyline_2way',participant_id:null,selection:'',line:null,period:'full_game',rules:'',rules_verified:false,sportsbook:'',observed_at:current(),retrieved_at:current(),source_published_at:null,source_ref:'',decimal_odds:2,status:'open',scope:page==='Live'?'live':'pregame',provenance:'manual_unverified',latency_seconds:null});
const wager=()=>({id:'unique-wager-id',external_id:null,event_id:'',event:'',sport:'',league:'',sportsbook:'',market:'moneyline_2way',selection:'',line:null,period:'full_game',rules:'',decimal_odds:2,stake:1,currency:'USD',placed_at:current(),source:'manual',mode:'paper',exposure_group:'event-id',research_snapshot_id:null,legs:[],notes:''});
async function api(path,body){let r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});let v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
function cell(v){let el=document.createElement('td');if(v===null||v===undefined)el.textContent='Unavailable';else if(typeof v==='object'){let p=document.createElement('pre');p.textContent=JSON.stringify(v,null,2);el.append(p);}else if(typeof v==='string'&&/^\d{4}-\d\d-\d\dT/.test(v))el.textContent=new Intl.DateTimeFormat('en-US',{dateStyle:'short',timeStyle:'medium',timeZone:$('zone').value}).format(new Date(v));else el.textContent=String(v);return el;}
function render(){let rows=Array.isArray(data)?data:[data];if(page==='Pregame')rows=rows.filter(r=>r.scope==='pregame');if(page==='Live')rows=rows.filter(r=>r.scope==='live');if(page==='Exposure')rows=rows.filter(r=>!r.settlement||r.settlement.provisional);let f=$('filter').value.toLowerCase();rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(f));$('view').replaceChildren();if(!rows.length){$('view').textContent=pages[page]==='research'?'No qualifying opportunities. Import research records to inspect missing evidence.':'No records.';return;}let table=document.createElement('table'),head=document.createElement('tr');let cols=page==='Discovery'||page==='Pregame'||page==='Live'?['sport','league','event','start_at','market','selection','line','period','rules','sportsbook','decimal_odds','best_observed_decimal','observed_at','implied_probability','model_probability','ev_per_unit','uncertainty','qualification','exclusion_reasons','snapshot_id','source_ref','expires_at']:Object.keys(rows[0]);cols.forEach(k=>{let th=document.createElement('th');th.textContent=k.replaceAll('_',' ');head.append(th);});table.append(head);rows.forEach(r=>{let tr=document.createElement('tr');cols.forEach(k=>tr.append(cell(r[k])));table.append(tr);});$('view').append(table);}
async function load(){try{data=await api(pages[page]);$('heading').textContent=page;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.textContent===page));$('note').textContent=page==='Performance'?'ROI = confirmed settled net profit ÷ confirmed settled stakes. Payout includes returned stake; fees deducted. Provisional results remain exposure. Currencies and paper/actual results stay separate. Drawdown uses settlement order.':page==='Live'?'Manual state imports only. No active feed, scheduler or alerts. Signals require aligned, fresh odds and state; no eligible models are configured.':'No probabilities or EV are inferred from imported prose or bookmaker disagreement.';let entry=['Discovery','Pregame','Live','Wagers','Limits'].includes(page);$('entry').hidden=!entry;if(entry){let obj=page==='Wagers'?wager():page==='Limits'?{currency:'USD',max_open:100,max_group:25,max_daily:50}:quote();$('recordType').value=page==='Wagers'?'wager':page==='Limits'?'limits':'quote';$('entryTitle').textContent=page==='Wagers'?'Enter wager or settlement correction':page==='Limits'?'Configure tracking limits':'Import one timestamped quote';$('entryNote').textContent=page==='Wagers'?'Modes: proposed, paper, actual. For settlement replace this JSON with id, revision (increasing), status, payout (including returned stake), fees, settled_at, source_ref, provisional (boolean), reason. A record logs a wager; it does not place a bet.':page==='Limits'?'Limits apply to actual wager entry; daily limits use UTC. These controls do not access or control sportsbook accounts.':'Manual imports remain unverified. Replace every placeholder with source facts. Do not mark demonstration records as authorized imports.';$('json').value=JSON.stringify(obj,null,2);}render();$('error').textContent='';}catch(e){$('error').textContent=e.message;}}
Object.keys(pages).forEach(p=>{let b=document.createElement('button');b.textContent=p;b.onclick=()=>{page=p;load();};$('nav').append(b);});
$('connect').onclick=async()=>{token=$('token').value;try{await api('health');$('login').hidden=true;$('app').hidden=false;$('token').value='';await load();}catch(e){token='';$('error').textContent=e.message;}};
$('logout').onclick=()=>{token='';data=[];$('view').replaceChildren();$('json').value='';$('app').hidden=true;$('login').hidden=false;};
$('refresh').onclick=load;$('filter').oninput=render;$('zone').onchange=render;
$('submit').onclick=async()=>{try{let obj=JSON.parse($('json').value);let route={quote:'quotes',state:'states',wager:'wagers',settlement:'settle',limits:'limits'}[$('recordType').value];let result=await api(route,obj);$('result').textContent=result.duplicate?'Duplicate ignored.':'Saved.';await load();}catch(e){$('result').textContent=e.message;}};

$('recordType').onchange=()=>{let type=$('recordType').value;let templates={quote:quote(),wager:wager(),state:{id:'unique-state-id',event_id:'',source_at:current(),retrieved_at:current(),period:'',clock:'',score:'',connected:false,mode:'manual',source_ref:''},settlement:{id:'existing-wager-id',revision:1,status:'win',payout:0,fees:0,settled_at:current(),source_ref:'',provisional:true,reason:''},limits:{currency:'USD',max_open:100,max_group:25,max_daily:50}};$('json').value=JSON.stringify(templates[type],null,2);};
