'use strict';
let token='',page='Discovery',data=[],loadRevision=0;
const $=id=>document.getElementById(id);
const pages={'Discovery':'research','Pregame':'research','Live':'research','Wagers':'wagers','Performance':'performance','Exposure':'wagers','Coverage':'coverage','Provider health':'health','Audit':'audit','Limits':'limits'};
const current=()=>new Date().toISOString();
const quote=()=>({id:crypto.randomUUID(),provider:'manual',provider_event_id:'',event_id:'',sport:'',league:'',event:'',start_at:current(),market:'moneyline_2way',participant_id:null,selection:'',line:null,period:'full_game',rules:'',rules_verified:false,sportsbook:'',observed_at:current(),retrieved_at:current(),source_published_at:null,source_ref:'',decimal_odds:2,status:'open',scope:page==='Live'?'live':'pregame',provenance:'manual_unverified',latency_seconds:null});
const wager=()=>({id:crypto.randomUUID(),external_id:null,event_id:'',event:'',sport:'',league:'',sportsbook:'',market:'moneyline_2way',selection:'',line:null,period:'full_game',rules:'',decimal_odds:2,stake:1,currency:'USD',placed_at:current(),source:'manual',mode:'paper',exposure_group:'',research_snapshot_id:null,legs:[],notes:''});
async function api(path,body){let r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});let v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
function cell(v){let el=document.createElement('td');if(v===null||v===undefined)el.textContent='Unavailable';else if(typeof v==='object'){let p=document.createElement('pre');p.textContent=JSON.stringify(v,null,2);el.append(p);}else if(typeof v==='string'&&/^\d{4}-\d\d-\d\dT/.test(v))el.textContent=new Intl.DateTimeFormat('en-US',{dateStyle:'short',timeStyle:'medium',timeZone:$('zone').value}).format(new Date(v));else el.textContent=String(v);return el;}
function render(){let rows=Array.isArray(data)?data:[data];if(page==='Pregame')rows=rows.filter(r=>r.scope==='pregame');if(page==='Live')rows=rows.filter(r=>r.scope==='live');if(page==='Exposure')rows=rows.filter(r=>!r.settlement||r.settlement.provisional);let f=$('filter').value.toLowerCase();rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(f));$('view').replaceChildren();if(!rows.length){$('view').textContent=pages[page]==='research'?'No qualifying opportunities. Import research records to inspect missing evidence.':'No records.';return;}let table=document.createElement('table'),head=document.createElement('tr');let cols=page==='Discovery'||page==='Pregame'||page==='Live'?['sport','league','event','start_at','market','selection','line','period','rules','sportsbook','decimal_odds','best_observed_decimal','observed_at','implied_probability','model_probability','ev_per_unit','uncertainty','qualification','exclusion_reasons','snapshot_id','source_ref','expires_at']:Object.keys(rows[0]);cols.forEach(k=>{let th=document.createElement('th');th.textContent=k.replaceAll('_',' ');head.append(th);});table.append(head);rows.forEach(r=>{let tr=document.createElement('tr');cols.forEach(k=>tr.append(cell(r[k])));table.append(tr);});$('view').append(table);}
async function load(){const revision=++loadRevision;const requestedPage=page;try{const response=await api(pages[requestedPage]);if(revision!==loadRevision||!token)return;data=response;$('heading').textContent=page;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.textContent===page));$('note').textContent=page==='Performance'?'ROI = confirmed settled net profit ÷ confirmed settled stakes. Payout includes returned stake; fees deducted. Provisional results remain exposure. Currencies and paper/actual results stay separate. Drawdown uses settlement order.':page==='Live'?'Manual state imports only. No active feed, scheduler or alerts. Signals require aligned, fresh odds and state; no eligible models are configured.':'No probabilities or EV are inferred from imported prose or bookmaker disagreement.';let entry=['Discovery','Pregame','Live','Wagers','Limits'].includes(page);$('entry').hidden=!entry;if(entry){let obj=page==='Wagers'?wager():page==='Limits'?{currency:'USD',max_open:100,max_group:25,max_daily:50}:quote();$('recordType').value=page==='Wagers'?'wager':page==='Limits'?'limits':'quote';$('entryTitle').textContent=page==='Wagers'?'Enter wager or settlement correction':page==='Limits'?'Configure tracking limits':'Import one timestamped quote';$('entryNote').textContent=page==='Wagers'?'Modes: proposed, paper, actual. Select Settlement to record payouts or corrections. Payout includes returned stake. A record logs a wager; it does not place a bet.':page==='Limits'?'Limits apply to actual wager entry; daily limits use UTC. These controls do not access or control sportsbook accounts.':'Manual imports remain unverified. Enter source facts, not demonstration values. Fields with timestamps require ISO time and timezone.';setEditor(obj);}render();$('error').textContent='';}catch(e){if(revision===loadRevision)$('error').textContent=e.message;}}
Object.keys(pages).forEach(p=>{let b=document.createElement('button');b.textContent=p;b.onclick=()=>{page=p;load();};$('nav').append(b);});
$('connect').onclick=async()=>{token=$('token').value;try{await api('health');$('login').hidden=true;$('app').hidden=false;$('token').value='';await load();}catch(e){token='';$('error').textContent=e.message;}};
$('logout').onclick=()=>{token='';loadRevision++;data=[];$('view').replaceChildren();$('json').value='';$('fields').replaceChildren();$('result').textContent='';$('app').hidden=true;$('login').hidden=false;};
$('refresh').onclick=load;$('filter').oninput=render;$('zone').onchange=render;
$('submit').onclick=async()=>{try{let obj=readEditor();let route={quote:'quotes',state:'states',wager:'wagers',settlement:'settle',limits:'limits'}[$('recordType').value];$('submit').disabled=true;let result=await api(route,obj);$('result').textContent=result.duplicate?'Duplicate ignored.':'Saved.';await load();}catch(e){$('result').textContent=e.message;}finally{$('submit').disabled=false;}};

$('recordType').onchange=()=>{let type=$('recordType').value;let templates={quote:quote(),wager:wager(),state:{id:crypto.randomUUID(),event_id:'',source_at:current(),retrieved_at:current(),period:'',clock:'',score:'',connected:false,mode:'manual',source_ref:''},settlement:{id:'',revision:1,status:'win',payout:0,fees:0,settled_at:current(),source_ref:'',provisional:true,reason:''},limits:{currency:'USD',max_open:100,max_group:25,max_daily:50}};setEditor(templates[type]);};
const options={market:['moneyline_2way','moneyline_3way','spread','alternate_spread','total','team_total','player_prop','game_prop','team_prop','period','futures','parlay','same_game_parlay'],mode:['proposed','paper','actual'],scope:['pregame','live'],provenance:['manual_unverified','authorized_import','demonstration']};
let editorBase={};
function setEditor(obj){editorBase=obj;$('json').value=JSON.stringify(obj,null,2);$('fields').replaceChildren();for(const [key,value] of Object.entries(obj)){let label=document.createElement('label');label.textContent=key.replaceAll('_',' ');let input;let choices=options[key];if(key==='mode'&&$('recordType').value==='state')choices=['manual','polling','streaming'];if(key==='status')choices=$('recordType').value==='settlement'?['win','loss','push','void','cashout','partial','dead_heat']:['open','suspended','closed','unknown'];if(choices){input=document.createElement('select');choices.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;input.append(o);});input.value=value;}else{input=document.createElement(Array.isArray(value)?'textarea':'input');if(typeof value==='boolean'){input.type='checkbox';input.checked=value;}else{input.value=Array.isArray(value)?JSON.stringify(value):value??'';if(typeof value==='number'){input.type='number';input.step='any';}}}input.dataset.key=key;label.append(input);$('fields').append(label);}toggleEditor();}
function readEditor(){if($('editorMode').value==='json')return JSON.parse($('json').value);let obj={...editorBase};for(let input of $('fields').querySelectorAll('[data-key]')){let key=input.dataset.key;let original=editorBase[key];obj[key]=typeof original==='boolean'?input.checked:Array.isArray(original)?JSON.parse(input.value):typeof original==='number'?Number(input.value):original===null&&input.value===''?null:input.value;}return obj;}
function toggleEditor(){$('fields').hidden=$('editorMode').value==='json';$('json').hidden=$('editorMode').value!=='json';}
$('editorMode').onchange=()=>{try{if($('editorMode').value==='json'){$('editorMode').value='fields';$('json').value=JSON.stringify(readEditor(),null,2);$('editorMode').value='json';toggleEditor();}else setEditor(JSON.parse($('json').value));}catch(e){$('result').textContent=e.message;}};
$('fields').onsubmit=e=>{e.preventDefault();$('submit').click();};
